jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /cinemaa
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:postgresql://127.0.0.1:5432/cinema
      username: postgres
      password: Campeon12
      hikari:
         poolName: pool
